I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 479, in script
    with Pause(2.5)
Exception: Possible infinite loop.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 479, in script
    with Pause(2.5)
  File "C:\Users\YousraKiran\Downloads\renpy-7.3.5-sdk\renpy\execution.py", line 59, in check_infinite_loop
    raise Exception("Possible infinite loop.")
Exception: Possible infinite loop.

Windows-8-6.2.9200
Ren'Py 7.3.5.606
The Begining After The End 1.0
Mon Nov 30 02:56:20 2020
